import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";

const adapter = new PrismaLibSql({
  url: process.env.DATABASE_URL ?? "file:./dev.db",
  authToken: process.env.TURSO_AUTH_TOKEN,
});
const prisma = new PrismaClient({ adapter });

type ItemSeed = {
  name: string;
  icon: string;
  category: "Clothing" | "Food" | "Hygiene" | "School supplies" | "Household";
  condition: "New only" | "New or used";
  note: string;
  highNeed?: boolean;
};

type CharitySeed = {
  slug: string;
  name: string;
  cause: string;
  rating: number;
  reviewCount: number;
  foundingYear: number;
  supportersCount: number;
  shortDescription: string;
  bio: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  lat: number;
  lng: number;
  phone: string;
  email: string;
  website: string;
  hours: string;
  logoInitial: string;
  verified?: boolean;
  items: ItemSeed[];
};

const clothingPool: ItemSeed[] = [
  { name: "Socks", icon: "🧦", category: "Clothing", condition: "New or used", note: "All sizes — kids and adult", highNeed: true },
  { name: "Winter coats", icon: "🧥", category: "Clothing", condition: "New or used", note: "Clean, zippers working", highNeed: true },
  { name: "Jeans & pants", icon: "👖", category: "Clothing", condition: "New or used", note: "Adult sizes especially needed" },
  { name: "Work boots", icon: "🥾", category: "Clothing", condition: "New or used", note: "Steel-toe preferred, all sizes" },
  { name: "Children's shoes", icon: "👟", category: "Clothing", condition: "New or used", note: "Sizes 5-13 kids most needed" },
];
const foodPool: ItemSeed[] = [
  { name: "Canned vegetables", icon: "🥫", category: "Food", condition: "New only", note: "Unexpired, unopened", highNeed: true },
  { name: "Rice & pasta", icon: "🍚", category: "Food", condition: "New only", note: "Sealed packages" },
  { name: "Peanut butter", icon: "🥜", category: "Food", condition: "New only", note: "Unexpired, unopened" },
  { name: "Baby formula", icon: "🍼", category: "Food", condition: "New only", note: "Unopened, unexpired", highNeed: true },
  { name: "Cooking oil", icon: "🫗", category: "Food", condition: "New only", note: "Sealed bottles" },
];
const hygienePool: ItemSeed[] = [
  { name: "Toothbrushes & toothpaste", icon: "🪥", category: "Hygiene", condition: "New only", note: "Sealed in packaging", highNeed: true },
  { name: "Soap & shampoo", icon: "🧴", category: "Hygiene", condition: "New only", note: "Travel or full size" },
  { name: "Diapers & wipes", icon: "🧷", category: "Hygiene", condition: "New only", note: "All sizes, unopened packs", highNeed: true },
  { name: "Feminine hygiene products", icon: "🩹", category: "Hygiene", condition: "New only", note: "Sealed packaging" },
];
const schoolPool: ItemSeed[] = [
  { name: "Backpacks", icon: "🎒", category: "School supplies", condition: "New or used", note: "Good condition, working straps" },
  { name: "Notebooks & pencils", icon: "📓", category: "School supplies", condition: "New only", note: "For fall school drive" },
  { name: "Calculators", icon: "🧮", category: "School supplies", condition: "New or used", note: "Working batteries a plus" },
  { name: "Children's books", icon: "📚", category: "School supplies", condition: "New or used", note: "Ages 4-12, gently used ok" },
];
const householdPool: ItemSeed[] = [
  { name: "Blankets", icon: "🛏️", category: "Household", condition: "New or used", note: "Freshly laundered" },
  { name: "Pots & pans", icon: "🍳", category: "Household", condition: "New or used", note: "Complete sets preferred" },
  { name: "Towels", icon: "🧻", category: "Household", condition: "New or used", note: "Bath size, clean" },
  { name: "Pet food & bedding", icon: "🐾", category: "Household", condition: "New or used", note: "Unopened bags or clean bedding", highNeed: true },
  { name: "Cleaning supplies", icon: "🧽", category: "Household", condition: "New only", note: "Unopened bottles" },
];

function pick(pool: ItemSeed[], ...idx: number[]) {
  return idx.map((i) => pool[i]);
}

const charities: CharitySeed[] = [
  {
    slug: "hope-south-bay",
    name: "Helping Others Prosper Everywhere",
    cause: "Community aid",
    rating: 4.9,
    reviewCount: 212,
    foundingYear: 2011,
    supportersCount: 3400,
    shortDescription: "Community aid",
    bio: "HOPE runs neighborhood programs for food security, job training, and family support across the South Bay. We operate a community pantry, a clothing closet, and weekly job-readiness workshops — everything donated goes directly to families within 10 miles of our center.",
    street: "1284 Willow Street",
    city: "San Jose",
    state: "CA",
    zip: "95112",
    lat: 37.3382,
    lng: -121.8863,
    phone: "(408) 555-0142",
    email: "hello@hopesouthbay.org",
    website: "hopesouthbay.org",
    hours: "Mon–Sat, 9am–5pm",
    logoInitial: "H",
    items: [...pick(clothingPool, 0, 1, 2), ...pick(foodPool, 0, 1), ...pick(hygienePool, 0, 1), ...pick(schoolPool, 0), ...pick(householdPool, 0, 1)],
  },
  {
    slug: "open-shelter-alliance",
    name: "Open Shelter Alliance",
    cause: "Housing",
    rating: 4.7,
    reviewCount: 98,
    foundingYear: 2008,
    supportersCount: 1900,
    shortDescription: "Housing",
    bio: "Open Shelter Alliance provides emergency shelter and transitional housing for families across Santa Clara County, alongside case management to help residents find permanent homes.",
    street: "455 Homestead Road",
    city: "Santa Clara",
    state: "CA",
    zip: "95050",
    lat: 37.3541,
    lng: -121.9552,
    phone: "(408) 555-0198",
    email: "info@openshelteralliance.org",
    website: "openshelteralliance.org",
    hours: "Mon–Fri, 8am–6pm",
    logoInitial: "O",
    items: [...pick(householdPool, 0, 1, 2), ...pick(clothingPool, 0, 1), ...pick(hygienePool, 0, 2)],
  },
  {
    slug: "bright-meals-network",
    name: "Bright Meals Network",
    cause: "Hunger relief",
    rating: 4.8,
    reviewCount: 154,
    foundingYear: 2014,
    supportersCount: 2600,
    shortDescription: "Hunger relief",
    bio: "Bright Meals Network rescues surplus food from grocers and restaurants, delivering roughly 20,000 meals a month to neighbors facing food insecurity across the South Bay.",
    street: "781 Kiely Boulevard",
    city: "Santa Clara",
    state: "CA",
    zip: "95051",
    lat: 37.3496,
    lng: -121.9752,
    phone: "(408) 555-0176",
    email: "hello@brightmeals.org",
    website: "brightmeals.org",
    hours: "Tue–Sun, 7am–3pm",
    logoInitial: "B",
    items: [...pick(foodPool, 0, 1, 2, 3, 4)],
  },
  {
    slug: "rivertown-youth-fund",
    name: "Rivertown Youth Fund",
    cause: "Education",
    rating: 4.6,
    reviewCount: 73,
    foundingYear: 2016,
    supportersCount: 980,
    shortDescription: "Education",
    bio: "Rivertown Youth Fund runs after-school tutoring and awards scholarships to first-generation college students throughout Campbell and the surrounding area.",
    street: "300 Orchard City Drive",
    city: "Campbell",
    state: "CA",
    zip: "95008",
    lat: 37.2872,
    lng: -121.95,
    phone: "(408) 555-0114",
    email: "team@rivertownyouth.org",
    website: "rivertownyouth.org",
    hours: "Mon–Fri, 2pm–7pm",
    logoInitial: "R",
    items: [...pick(schoolPool, 0, 1, 2, 3)],
  },
  {
    slug: "greenpath-foundation",
    name: "GreenPath Foundation",
    cause: "Health",
    rating: 4.5,
    reviewCount: 61,
    foundingYear: 2013,
    supportersCount: 740,
    shortDescription: "Health",
    bio: "GreenPath Foundation runs a fleet of mobile health screening vans, bringing free blood pressure, glucose, and vision screenings to underserved neighborhoods across the region.",
    street: "1500 Serra Way",
    city: "Milpitas",
    state: "CA",
    zip: "95035",
    lat: 37.4323,
    lng: -121.8996,
    phone: "(408) 555-0133",
    email: "contact@greenpathfoundation.org",
    website: "greenpathfoundation.org",
    hours: "Mon–Sat, 8am–4pm",
    logoInitial: "G",
    items: [...pick(hygienePool, 0, 1, 3), ...pick(householdPool, 4)],
  },
  {
    slug: "bay-area-paws-rescue",
    name: "Bay Area Paws Rescue",
    cause: "Animals",
    rating: 4.8,
    reviewCount: 187,
    foundingYear: 2009,
    supportersCount: 2100,
    shortDescription: "Animals",
    bio: "Bay Area Paws Rescue fosters and rehomes abandoned dogs and cats, and runs a low-cost spay/neuter clinic to keep local shelters from overflowing.",
    street: "899 Kifer Road",
    city: "Sunnyvale",
    state: "CA",
    zip: "94086",
    lat: 37.3688,
    lng: -122.0363,
    phone: "(408) 555-0161",
    email: "adopt@bayareapaws.org",
    website: "bayareapaws.org",
    hours: "Wed–Mon, 10am–5pm",
    logoInitial: "P",
    items: [...pick(householdPool, 3, 2, 0)],
  },
  {
    slug: "second-harvest-neighbors",
    name: "Second Harvest Neighbors",
    cause: "Hunger relief",
    rating: 4.7,
    reviewCount: 132,
    foundingYear: 2005,
    supportersCount: 3100,
    shortDescription: "Hunger relief",
    bio: "Second Harvest Neighbors stocks a weekly free grocery market and delivers shelf-stable staples to homebound seniors across Mountain View.",
    street: "600 Ellis Street",
    city: "Mountain View",
    state: "CA",
    zip: "94043",
    lat: 37.3861,
    lng: -122.0839,
    phone: "(650) 555-0122",
    email: "info@secondharvestneighbors.org",
    website: "secondharvestneighbors.org",
    hours: "Mon, Wed, Fri, 9am–1pm",
    logoInitial: "S",
    items: [...pick(foodPool, 0, 1, 2, 4)],
  },
  {
    slug: "greenleaf-conservation-corps",
    name: "GreenLeaf Conservation Corps",
    cause: "Environment",
    rating: 4.6,
    reviewCount: 54,
    foundingYear: 2017,
    supportersCount: 610,
    shortDescription: "Environment",
    bio: "GreenLeaf Conservation Corps organizes creek cleanups, native tree plantings, and watershed restoration projects with volunteers across the Peninsula.",
    street: "250 Hamilton Avenue",
    city: "Palo Alto",
    state: "CA",
    zip: "94301",
    lat: 37.4419,
    lng: -122.143,
    phone: "(650) 555-0187",
    email: "volunteer@greenleafcorps.org",
    website: "greenleafcorps.org",
    hours: "Sat–Sun, 8am–1pm",
    logoInitial: "L",
    items: [...pick(householdPool, 4), ...pick(clothingPool, 3)],
  },
  {
    slug: "south-bay-literacy-project",
    name: "South Bay Literacy Project",
    cause: "Education",
    rating: 4.9,
    reviewCount: 88,
    foundingYear: 2010,
    supportersCount: 1200,
    shortDescription: "Education",
    bio: "South Bay Literacy Project pairs trained volunteer tutors with adult learners working toward English fluency, GED completion, and citizenship exams.",
    street: "10300 Torre Avenue",
    city: "Cupertino",
    state: "CA",
    zip: "95014",
    lat: 37.323,
    lng: -122.0322,
    phone: "(408) 555-0145",
    email: "hello@sblliteracy.org",
    website: "sblliteracy.org",
    hours: "Mon–Thu, 4pm–8pm",
    logoInitial: "L",
    items: [...pick(schoolPool, 1, 3)],
  },
  {
    slug: "safe-haven-family-shelter",
    name: "Safe Haven Family Shelter",
    cause: "Housing",
    rating: 4.8,
    reviewCount: 121,
    foundingYear: 2003,
    supportersCount: 1650,
    shortDescription: "Housing",
    bio: "Safe Haven Family Shelter provides confidential emergency housing and counseling for survivors of domestic violence, plus a 24-hour crisis line.",
    street: "39150 Liberty Street",
    city: "Fremont",
    state: "CA",
    zip: "94538",
    lat: 37.5485,
    lng: -121.9886,
    phone: "(510) 555-0119",
    email: "support@safehavenshelter.org",
    website: "safehavenshelter.org",
    hours: "24/7 crisis line",
    logoInitial: "S",
    items: [...pick(householdPool, 0, 2), ...pick(hygienePool, 2, 3), ...pick(clothingPool, 4)],
  },
  {
    slug: "valley-free-clinic",
    name: "Valley Free Clinic",
    cause: "Health",
    rating: 4.7,
    reviewCount: 96,
    foundingYear: 1999,
    supportersCount: 2050,
    shortDescription: "Health",
    bio: "Valley Free Clinic offers no-cost primary care, dental checkups, and prescription assistance to uninsured residents of the West Valley.",
    street: "15400 Los Gatos Boulevard",
    city: "Los Gatos",
    state: "CA",
    zip: "95032",
    lat: 37.2358,
    lng: -121.9624,
    phone: "(408) 555-0159",
    email: "care@valleyfreeclinic.org",
    website: "valleyfreeclinic.org",
    hours: "Mon–Fri, 9am–6pm",
    logoInitial: "V",
    items: [...pick(hygienePool, 0, 1, 2)],
  },
  {
    slug: "neighbors-helping-neighbors",
    name: "Neighbors Helping Neighbors",
    cause: "Community aid",
    rating: 4.6,
    reviewCount: 67,
    foundingYear: 2012,
    supportersCount: 890,
    shortDescription: "Community aid",
    bio: "Neighbors Helping Neighbors provides emergency rent assistance, a community closet, and a volunteer repair crew for elderly and disabled residents of Morgan Hill.",
    street: "17575 Peak Avenue",
    city: "Morgan Hill",
    state: "CA",
    zip: "95037",
    lat: 37.1305,
    lng: -121.6544,
    phone: "(408) 555-0171",
    email: "info@neighborshelpingmh.org",
    website: "neighborshelpingmh.org",
    hours: "Tue–Sat, 10am–4pm",
    logoInitial: "N",
    items: [...pick(clothingPool, 0, 1), ...pick(foodPool, 1, 2), ...pick(householdPool, 0, 1)],
  },
  {
    slug: "coastal-wildlife-rescue",
    name: "Coastal Wildlife Rescue",
    cause: "Animals",
    rating: 4.9,
    reviewCount: 143,
    foundingYear: 2001,
    supportersCount: 1780,
    shortDescription: "Animals",
    bio: "Coastal Wildlife Rescue rehabilitates injured birds, marine mammals, and small wildlife found along the Peninsula shoreline before releasing them back into the wild.",
    street: "2100 Bay Road",
    city: "Redwood City",
    state: "CA",
    zip: "94063",
    lat: 37.4852,
    lng: -122.2364,
    phone: "(650) 555-0138",
    email: "rescue@coastalwildlife.org",
    website: "coastalwildlife.org",
    hours: "Daily, 8am–6pm",
    logoInitial: "C",
    items: [...pick(householdPool, 2, 3)],
  },
  {
    slug: "golden-gate-food-bank",
    name: "Golden Gate Food Bank",
    cause: "Hunger relief",
    rating: 4.8,
    reviewCount: 340,
    foundingYear: 1985,
    supportersCount: 8200,
    shortDescription: "Hunger relief",
    bio: "Golden Gate Food Bank distributes food through a network of 200+ partner pantries and schools, serving over 50,000 households a month across the Bay Area.",
    street: "900 Pennsylvania Avenue",
    city: "San Francisco",
    state: "CA",
    zip: "94107",
    lat: 37.7749,
    lng: -122.4194,
    phone: "(415) 555-0104",
    email: "info@goldengatefoodbank.org",
    website: "goldengatefoodbank.org",
    hours: "Mon–Sat, 7am–5pm",
    logoInitial: "G",
    items: [...pick(foodPool, 0, 1, 2, 3, 4)],
  },
  {
    slug: "bright-futures-scholars",
    name: "Bright Futures Scholars",
    cause: "Education",
    rating: 4.7,
    reviewCount: 59,
    foundingYear: 2015,
    supportersCount: 520,
    shortDescription: "Education",
    bio: "Bright Futures Scholars awards need-based college scholarships and provides FAFSA workshops for first-generation students in the Peninsula school districts.",
    street: "701 Laurel Street",
    city: "Menlo Park",
    state: "CA",
    zip: "94025",
    lat: 37.453,
    lng: -122.1817,
    phone: "(650) 555-0193",
    email: "hello@brightfuturesscholars.org",
    website: "brightfuturesscholars.org",
    hours: "Mon–Fri, 9am–5pm",
    logoInitial: "F",
    items: [...pick(schoolPool, 0, 2, 3)],
  },
  {
    slug: "east-bay-housing-alliance",
    name: "East Bay Housing Alliance",
    cause: "Housing",
    rating: 4.5,
    reviewCount: 84,
    foundingYear: 1994,
    supportersCount: 2300,
    shortDescription: "Housing",
    bio: "East Bay Housing Alliance advocates for affordable housing policy and operates a transitional shelter for individuals exiting homelessness in Oakland.",
    street: "1918 Telegraph Avenue",
    city: "Oakland",
    state: "CA",
    zip: "94612",
    lat: 37.8044,
    lng: -122.2712,
    phone: "(510) 555-0147",
    email: "contact@eastbayhousing.org",
    website: "eastbayhousing.org",
    hours: "Mon–Fri, 8:30am–5:30pm",
    logoInitial: "E",
    items: [...pick(householdPool, 0, 1, 2), ...pick(clothingPool, 1, 3)],
  },
  {
    slug: "green-bay-cleanup-crew",
    name: "Green Bay Cleanup Crew",
    cause: "Environment",
    rating: 4.4,
    reviewCount: 41,
    foundingYear: 2019,
    supportersCount: 380,
    shortDescription: "Environment",
    bio: "Green Bay Cleanup Crew runs monthly shoreline and storm-drain cleanups around the East Bay, removing plastic waste before it reaches the Bay.",
    street: "160 University Avenue",
    city: "Berkeley",
    state: "CA",
    zip: "94710",
    lat: 37.8715,
    lng: -122.273,
    phone: "(510) 555-0129",
    email: "hello@greenbaycleanup.org",
    website: "greenbaycleanup.org",
    hours: "First Saturday monthly, 9am–12pm",
    logoInitial: "G",
    items: [...pick(householdPool, 4), ...pick(hygienePool, 1)],
  },
  {
    slug: "companion-animal-alliance",
    name: "Companion Animal Alliance",
    cause: "Animals",
    rating: 4.6,
    reviewCount: 77,
    foundingYear: 2006,
    supportersCount: 940,
    shortDescription: "Animals",
    bio: "Companion Animal Alliance runs a low-cost spay/neuter clinic and weekend adoption events to reduce shelter intake across the Tri-City area.",
    street: "33000 Alvarado-Niles Road",
    city: "Union City",
    state: "CA",
    zip: "94587",
    lat: 37.5934,
    lng: -122.0439,
    phone: "(510) 555-0156",
    email: "adopt@companionanimalalliance.org",
    website: "companionanimalalliance.org",
    hours: "Thu–Mon, 11am–5pm",
    logoInitial: "A",
    items: [...pick(householdPool, 3, 2)],
  },
  {
    slug: "harvest-home-pantry",
    name: "Harvest Home Pantry",
    cause: "Hunger relief",
    rating: 4.7,
    reviewCount: 65,
    foundingYear: 2007,
    supportersCount: 710,
    shortDescription: "Hunger relief",
    bio: "Harvest Home Pantry stocks a free grocery pantry for farmworker families and seasonal laborers throughout rural Gilroy and South County.",
    street: "7981 Church Street",
    city: "Gilroy",
    state: "CA",
    zip: "95020",
    lat: 37.0058,
    lng: -121.5683,
    phone: "(408) 555-0182",
    email: "info@harvesthomepantry.org",
    website: "harvesthomepantry.org",
    hours: "Tue & Thu, 9am–2pm",
    logoInitial: "H",
    items: [...pick(foodPool, 1, 2, 3, 4)],
  },
  {
    slug: "healthy-start-mobile-clinic",
    name: "Healthy Start Mobile Clinic",
    cause: "Health",
    rating: 4.8,
    reviewCount: 102,
    foundingYear: 2018,
    supportersCount: 690,
    shortDescription: "Health",
    bio: "Healthy Start Mobile Clinic brings free pediatric checkups, vaccinations, and vision screenings directly to schools and community centers in Newark.",
    street: "36600 Cedar Boulevard",
    city: "Newark",
    state: "CA",
    zip: "94560",
    lat: 37.5297,
    lng: -122.0402,
    phone: "(510) 555-0163",
    email: "care@healthystartmobile.org",
    website: "healthystartmobile.org",
    hours: "Mon–Fri, 8am–3pm",
    logoInitial: "M",
    items: [...pick(hygienePool, 0, 2, 3), ...pick(foodPool, 3)],
  },
];

const ads = [
  {
    slot: "banner",
    label: "SPONSORED",
    text: "Double your impact this July — GiveWell Partners matches every first donation up to $100.",
    ctaText: "Learn more",
    linkUrl: "https://example.org/givewell-match",
    weight: 2,
  },
  {
    slot: "banner",
    label: "SPONSORED",
    text: "New: track every donation's impact in real time with the Donation Location mobile app.",
    ctaText: "Get the app",
    linkUrl: "https://example.org/mobile-app",
    weight: 1,
  },
  {
    slot: "inline",
    label: "PROMOTED",
    text: "Employers can match your gifts automatically. Check if yours participates →",
    ctaText: null,
    linkUrl: "https://example.org/employer-match",
    weight: 2,
  },
  {
    slot: "inline",
    label: "PROMOTED",
    text: "Set up a recurring monthly gift and 3x your yearly impact on the causes you love →",
    ctaText: null,
    linkUrl: "https://example.org/recurring-gift",
    weight: 1,
  },
];

async function main() {
  console.log("Seeding database...");
  await prisma.pledge.deleteMany();
  await prisma.wishlistItem.deleteMany();
  await prisma.charity.deleteMany();
  await prisma.ad.deleteMany();
  await prisma.user.deleteMany();

  for (const c of charities) {
    const { items, ...charityData } = c;
    await prisma.charity.create({
      data: {
        ...charityData,
        items: { create: items },
      },
    });
  }

  for (const ad of ads) {
    await prisma.ad.create({ data: ad });
  }

  console.log(`Seeded ${charities.length} charities and ${ads.length} ads.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
